### ISSUE TITLE
Trying injectMetaTagsLambdaFunction

### ISSUE THREAD

**Issue by jovana** [echowaves/WiSaw.cdk#10]
Hi, thanks for sharing your code. 
I'm trying to understand the injectMetaTagsLambdaFunction. Also, I have set up a test environment for this. 

For some reason, it seems to replace only the static files and not the index.html I want to have replaced the meta tags in the index.html file as you do.

You can see the attached image it has replaced the favicon.png and it contains HTML code (CSS and other images have this). It has the code I give from the lambda function (you see in the title it has "META INJECTOR").

<img width="1164" alt="Scherm­afbeelding 2023-10-05 om 11 52 15" src="https://github.com/echowaves/WiSaw.cdk/assets/645456/f7932f11-d66e-4e69-881c-8976e112c635">

What I'm missing here? Any help is very welcome!

thx!

**Comment by jovana** [comment]
💡 Suddenly I had an idea why it is not working. I have set up a separate ```cache_behavior``` for the index.html. And this does not have the ```lambda_function_association```! 

This is the fix to have it working:
```
  ordered_cache_behavior {
    path_pattern           = "/index.html" 
   // other config

    lambda_function_association {
      event_type = "viewer-request"
      lambda_arn = <your lambda arn>
    }
}
```

Thx anyway on sharing your code!

**Comment by dmitryame** [comment]
Awesome, I was just typing my response, but glad you were able to figure out out. 
One more thing to point out:
it only works for me with  `runtime: lambda.Runtime.NODEJS_16_X`, I tried to switch it to the 18 and it fails (didn't have time to dig into it yet). 
Cheers!
